import './global.css';
import { Raleway } from 'next/font/google'
import { ThemeProvider } from '@deploy/shared/components/common/theme/theme-provider'
import { Toaster } from '@deploy/shared/components/ui/toaster';
import { Toaster as SonnerToaster } from '@deploy/shared/components/ui/sonner';
const font = Raleway({ subsets: ['latin'] });

export const metadata = {
  title: 'Welcome to Deploy',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={font.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
            {/* <Toaster/>    */}
            {/* <SonnerToaster/>    */}
          {children}
        </ThemeProvider></body>
    </html>
  );
}
