import './global.css';
import { Raleway } from 'next/font/google'
import { ThemeProvider } from '@deploy/shared/components/common/theme/theme-provider'
import { Toaster } from '@deploy/shared/components/ui/toaster';
import { Toaster as SonnerToaster } from '@deploy/shared/components/ui/sonner';
import Script from 'next/script';
const font = Raleway({ subsets: ['latin'] });
import PrelineScript from "@deploy/shared/components/extra/PrelineScript";
export const metadata = {
  title: 'Welcome to Deploy',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      {/* <Script src="./node_modules/preline/dist/preline.js" />      */}
      <body className={font.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {/* <Toaster/>    */}
          {/* <SonnerToaster/>    */}
          {children}
        </ThemeProvider>
      </body>
      <PrelineScript />
    </html>
  );
}
